server:
  port: 8001
mybatis:
  type-aliases-package: com.wuhen.springwork.model
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: springwork
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springwork?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useAffectedRows=true
    username: root
    password: root